services:
  - type: web
    name: task_manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
